idf_component_register(
    SRCS 
        "main.c"
        "audio.c"
        "buttons.c"
        "encoder.c"
        "navigation.c"
        "sd_card.c"
        "announcements.c"
        "headphone_detect.c"
        "usb_msc.c"
        "SD_CARD_OTA.c"
        "battery.c"
        "quiz.c"
    INCLUDE_DIRS "."
)